# Generated by Django 5.1.3 on 2024-11-08 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
    ]
