# Generated by Django 5.1.3 on 2024-11-05 19:22

from django.db import migrations

def populate_team(apps, schemaeditor):
    entries = {
        "alpha": "the A team",
        "bravo": "the B team",
        "charlie": "the C team"
    }
    Team = apps.get_model("accounts", "Team")
    for key, value in entries.items():
        team = Team(name=key, description=value)
        team.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20241105_1122'),
    ]

    operations = [
        migrations.RunPython(populate_team)
    ]
